### ISSUE TITLE
Slave - 서버와 통신

### ISSUE THREAD

**Issue by Jin02** [DKUMSE/Lock#10]
DevicePolicyManager, KeyGuardManager 활용에 앞서,
백그라운드 서비스를 만들고 #7 과 연계하여 데이터를 받는 작업을 우선적으로 구현한다.

**Comment by Jin02** [comment]
참고 자료:
http://iw90.tistory.com/155
http://bitsoul.tistory.com/147

**Comment by zeroseok** [comment]
전부 개발 완료 후 master에 올렸습니다.
