### ISSUE TITLE
slave UI

### ISSUE THREAD

**Issue by rkdaudcjf123** [DKUMSE/Lock#11]
슬레이브 UI 만들다가 에러가 계속나서 일단 올립니다.
ID,PASSWORD,로그인,회원가입 만들어봤습니다

**Comment by Jin02** [comment]
이슈 내용에 현재 어떤 것을 개발하고 있는지 적어주시고, Label, Assignees 업데이트 해주세요. ㅜㅜ

아까 강의 시작 전에 확인한 프로젝트에서 API 버전으로 인한 문제가 있었으니까 그거 고려하셔서 다시 개발하시면 될 것 같습니다.

**Comment by rkdaudcjf123** [comment]
락스크린, ui,백그라운드 스레드 했습니다. 여기서  아이디비밀번호 서버에 저장,master에서 로그아웃하면 slv 화면 풀림기능 필요합니다
