### ISSUE TITLE
Master UI 개발

### ISSUE THREAD

**Issue by Jin02** [DKUMSE/Lock#4]
Master UI를 개발합니다.
이전에 설명했던 Activity 구성하면 됩니다.

**Comment by zeroseok** [comment]
현재 작업 중
![Imgur](https://i.imgur.com/l8MP4iq.png)
![Imgur](https://i.imgur.com/clSb70X.png)

**Comment by zeroseok** [comment]
로그인 화면 웹서버 연결전 (수정)
![1-1](https://user-images.githubusercontent.com/39550422/41190767-aeea3390-6c1f-11e8-8beb-794a7f0ec3e0.PNG)
![1-2](https://user-images.githubusercontent.com/39550422/41190771-b1769c48-6c1f-11e8-8f8c-bf5347e7d2a9.PNG)

**Comment by zeroseok** [comment]
#4와 연관 코드
웹서버 연결전 작업

**Comment by zeroseok** [comment]
The final Master UI -End-
