### ISSUE TITLE
회원가입 만들기

### ISSUE THREAD

**Issue by sojinchu** [DKUMSE/Lock#6]
회원가입 했을 때 insert로 받기
sql을 사용하여 추가한다.

**Comment by Jin02** [comment]
가입은 POST로 받으시고 id, pw 받으시면 됩니다.
DB에서 미리 테이블 하나 만드실때 튜플 구성은 id, pw, isLock 3개로 두시면 되고 vchar, vchar, bool 로 타입 설정하시면 됩니다.

보안 이슈는 제가 나중에 직접 구현할테니 일단 이 형식 맞춰서 구현하시면 됩니다.

----
flask에서 db는 SQLAlchemy을 주로 사용한다고 하니 아래 링크 참고하시면서 개발하면 됩니다.
http://flask-sqlalchemy.pocoo.org/2.3/quickstart/
