### ISSUE TITLE
test 페이지 만들기

### ISSUE THREAD

**Issue by sojinchu** [DKUMSE/Lock#7]
테스트 페이지를 db를 이용하여 만들기

처음 접속하면 0 뜨고 두 번째 접속하면 1 뜨고 세 번째 접속하면 0 네 번째는 1 다섯 번째는 0 이런식으로 0과 1이 반복되게 만들기

불을 이용하여 만들기

셀렉트로 출력 db로 업데이트

이걸로 계속 반대값이 계속 출력되게 만든다.

**Comment by Jin02** [comment]
assam 서버에 mysql 세팅 끝났으니 개발 시작하면 됩니다.
